# Generated by Django 5.2.7 on 2025-10-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='course_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='sub_courses',
            field=models.CharField(max_length=200),
        ),
    ]
