# Generated by Django 5.2.7 on 2025-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0002_alter_category_course_name_alter_courses_sub_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=300)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])),
                ('Qualification', models.CharField(max_length=500)),
                ('Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Guardian', models.CharField(max_length=300)),
                ('Occupation', models.CharField(max_length=300)),
                ('Guardian_Mobile', models.IntegerField()),
                ('course', models.CharField()),
                ('Mode', models.CharField(choices=[('live online', 'Live online'), ('classrom', 'Classroom')], max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Registration',
            },
        ),
        migrations.CreateModel(
            name='timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
