# Generated by Django 5.2.7 on 2025-11-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0003_registration_timing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timing',
        ),
        migrations.AddField(
            model_name='registration',
            name='Pin',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.AddField(
            model_name='registration',
            name='time',
            field=models.CharField(default='Na', max_length=300),
        ),
        migrations.AlterField(
            model_name='registration',
            name='DOB',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Fullname',
            field=models.CharField(default='Na', max_length=300),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Gender',
            field=models.CharField(default='Na', max_length=300),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Guardian',
            field=models.CharField(default='Na', max_length=300),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Guardian_Mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Mode',
            field=models.CharField(default='Na', max_length=300),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Occupation',
            field=models.CharField(default='Na', max_length=300),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Qualification',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.CharField(default='Na', max_length=600),
        ),
    ]
