# Generated by Django 5.2.7 on 2025-11-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0004_delete_timing_registration_pin_registration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='loc',
            field=models.CharField(default='Na', max_length=300),
        ),
    ]
