# Generated by Django 5.2.7 on 2025-11-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0005_registration_loc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Fullname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Guardian',
            new_name='guardian',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Guardian_Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Mode',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Occupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Pin',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Qualification',
            new_name='qualification',
        ),
    ]
