# Generated by Django 5.2.7 on 2025-11-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0006_rename_dob_registration_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='number',
            field=models.CharField(default=0),
        ),
    ]
