# Generated by Django 5.2.7 on 2025-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0007_alter_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='hobbies',
            field=models.CharField(default='Na', max_length=300),
        ),
    ]
