# Generated by Django 5.2.7 on 2025-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0008_registration_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='file',
            field=models.FileField(default='NA', upload_to='documents'),
        ),
    ]
