# Generated by Django 5.2.7 on 2025-11-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0010_country_remove_registration_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scope.city'),
        ),
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scope.country'),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scope.state'),
        ),
    ]
