# Generated by Django 5.2.7 on 2025-11-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0011_registration_city_registration_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('mssg', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'contactdetails',
            },
        ),
    ]
