# Generated by Django 5.2.7 on 2025-11-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0012_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='country',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.CharField(default='Na', max_length=500),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
