# Generated by Django 5.2.7 on 2025-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0013_alter_registration_city_alter_registration_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='first_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('expire_time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
