# Generated by Django 5.2.7 on 2025-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0014_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_login',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
