# Generated by Django 5.2.7 on 2025-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0015_alter_first_login_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_login',
            name='confirm_password',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AddField(
            model_name='first_login',
            name='password',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
