# Generated by Django 5.2.7 on 2025-11-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0016_first_login_confirm_password_first_login_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='first_login',
        ),
        migrations.AddField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AddField(
            model_name='registration',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
