# Generated by Django 5.2.7 on 2025-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0017_delete_first_login_registration_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.TextField(blank=True, default='Na', null=True),
        ),
    ]
