# Generated by Django 5.2.7 on 2025-12-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0018_alter_registration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, default='No description available', null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(blank=True, default='TBD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='location',
            field=models.TextField(blank=True, default='Not available', null=True),
        ),
    ]
