# Generated by Django 5.2.7 on 2025-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0019_courses_description_courses_duration_courses_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(blank=True, default='6 Month + 3 Month OJT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=40000, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='location',
            field=models.TextField(blank=True, default='Kochi,Trivandum,Nagercoil', null=True),
        ),
    ]
